# Generated by Django 5.0.7 on 2024-07-22 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('product_code', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('stock', models.IntegerField()),
                ('image', models.ImageField(upload_to='product_image')),
            ],
        ),
    ]
