# Generated by Django 5.0.7 on 2024-07-23 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_todo_delete_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['id']},
        ),
    ]
